### ISSUE TITLE
Group 'package:Default' is not defined. Concept package:Default not found.

### ISSUE THREAD

**Issue by pmihalcin** [buschmais/jqa-spring-plugin#18]
When I copy & paste jqassistant-maven-plugin configuration from https://101.jqassistant.org/getting-started-spring-boot-maven/readme.html#MavenPlugin and run `mvn clean install`, I get `[ERROR] Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:analyze (default-cli) on project mer-web: Analysis failed.: Group 'package:Default' is not defined. Concept package:Default not found. -> [Help 1]`

Why is that?

I have to comment out `<group>package:Default</group>`, so that it returns constraint violations.

**Comment by StephanPirnbaum** [comment]
Hi,
the `package:Default` group refers to your project specific rules you can define under `/jqassistant` (See section 4 of the plugin documentation you linked to). So if you haven't defined one yourself you have to comment this one in the plugin configuration as you already figured out. 

The group `spring-boot:Strict`, e.g. is shipped with the spring plugin and thus can be found.

**Comment by pmihalcin** [comment]
Ah, thanks for the explanation.
From docs:
`defines the rule group spring-boot:Strict to be executed during analysis (alternatively spring-boot:Default, for package:Default see Project Specific Rules)`
This made me think `spring-boot:Default` is somehow in relationship with `package:Default`

`defines the rule group spring-boot:Strict to be executed during analysis (alternatively spring-
boot:Default), for package:Default see Project Specific Rules`
would be better :)

**Comment by DirkMahler** [comment]
Applied the suggested change, thanks!
