### ISSUE TITLE
Spring boot configuration properties report as FieldsOfInjectablesMustNotBeManipulated

### ISSUE THREAD

**Issue by pmihalcin** [buschmais/jqa-spring-plugin#19]
Given I have:
```
@ConfigurationProperties("security")
@Getter
@Setter
public class SecurityProperties {
    private boolean enabled = true;
}
```

When I run `jqassistant-maven-plugin:1.4.0:analyze (default-cli)`, then it reports:

```
[ERROR] --[ Constraint Violation ]-----------------------------------------
[ERROR] Constraint: spring-injection:FieldsOfInjectablesMustNotBeManipulated
[ERROR] Severity: MAJOR
[ERROR] Fields of injectable types must not be manipulated, except from constructors.
[ERROR]   Message=...SecurityProperties.setEnabled(?) writes field 'enabled' at line 13, Injectable=...SecurityProperties, Method=...SecurityProperties#void setEnabled(boolean), Field=...SecurityProperties#boolean enabled, LineNumber=13
```

The reason I have setters is [missing support for immutable `@ConfigurationProperties`](https://github.com/spring-projects/spring-boot/issues/8762).

**Comment by pmihalcin** [comment]
@olivergierke Have you come across this issue? Do you happen to know about any solution?

**Comment by meierval** [comment]
I have the same issues. Any updates on this?

**Comment by DirkMahler** [comment]
It seems that the issue for supporting immutable config properties has been solved. So one option could be upgrading the Spring boot version. But i guess that this very likely won't be a feasible option for you.

I see the following alternative options:

1. The upcoming jQA release introduces an annotation "jQASuppress"  which would allow suppressing the issue (similar to the annotations provided by Checkstyle, FindBugs, SonarQube etc).
2. The rule could be changed in a way that only constructors or setters are allowed to write such fields, furthermore the setters must not be called by anyone. Could become quite complex, maybe the more generic rule is that fields may only be manipulated by methods including constructors that are not called by invoked by anyone else.
3. The rule could explicitly exclude classes that are annotated as ConfigurationProperties. This sounds very specific and not desirable.

Any opinions on this?

**Comment by DirkMahler** [comment]
#19 Relaxed the constraint such that only fields of injectable types are checked for being written by non-constructor methods
