### ISSUE TITLE
Spock specifications not treated as tests

### ISSUE THREAD

**Issue by pmihalcin** [buschmais/jqa-spring-plugin#20]
Given I have:
```
@SpringBootTest
class MerchantImportExportSpec extends spock.lang.Specification {
    @Autowired
    MerchantService merchantService
    ...
}
```
plugin reports it as `[ERROR]   Message=null, Injectable=merchant.MerchantImportExportSpec, Method=merchant.MerchantImportExportSpec#void setMerchantService(merchant.MerchantService), Field=merchant.MerchantImportExportSpec#merchant.MerchantService merchantService, LineNumber=null`

This is test, so I'd expect I can inject using `@Autowired `.
Is it possible to tweak the rule so that it treats Spock specifications as tests as well?

**Comment by DirkMahler** [comment]
Should be obsolete now as Spock test shall be located in test artifacts which are no longer considered by the constraints. Any objections to close it?

**Comment by pmihalcin** [comment]
@DirkMahler Yes, this issue can be closed. Thanks for the fix!

**Comment by DirkMahler** [comment]
Thanks for the feedback!
