### ISSUE TITLE
Groovy class is reported as FieldsOfInjectablesMustNotBeManipulated

### ISSUE THREAD

**Issue by pmihalcin** [buschmais/jqa-spring-plugin#21]
When I create groovy class which is injectable, plugin reports `FieldsOfInjectablesMustNotBeManipulated `because of some `getMetaClass()` and `setMetaClass()` which is not in my control

```
[ERROR]   Message=null, Injectable=foo.WiremockLauncher$WiremockRunner, Method=foo.WiremockLauncher$WiremockRunner#groovy.lang.MetaClass getMetaClass(), Field=foo.WiremockLauncher$WiremockRunner#groovy.lang.MetaClass metaClass, LineNumber=null
```
```
[ERROR]   Message=null, Injectable=foo.WiremockLauncher$WiremockRunner, Method=foo.WiremockLauncher$WiremockRunner#void setMetaClass(groovy.lang.MetaClass), Field=foo.WiremockLauncher$WiremockRunner#groovy.lang.MetaClass metaClass, LineNumber=
```

**Comment by DirkMahler** [comment]
Your issue should been gone with 1.5.0-RC-1 (test code is no longer considered by this constraint), but still the problem persists how to deal with generated classes. Do you have an example application somewhere available that we could use to dig a bit deeper?

**Comment by pmihalcin** [comment]
@DirkMahler I pushed a sample [here](https://github.com/pmihalcin/groovy-jqa-spring-plugin-issue). 
`mvn clean verify` is enough to reproduce the issue.
Let me know if it works for you.

**Comment by DirkMahler** [comment]
Thanks a lot, will have a look into it!

**Comment by DirkMahler** [comment]
It worked like a charm and I could see the problem. The solution should be quite easy as well: the rules shall not consider all fields that have a property _synthetic_ (as generated by Groovy).

**Comment by DirkMahler** [comment]
The issue has been fixed, after upgrading the sample to jQA 1.5.0-RC-2-SNAPSHOT no violations are reported.

**Comment by pmihalcin** [comment]
@DirkMahler How can I reference snapshot repository?
I tried:
```
<repositories>
	<repository>
		<id>sonatype-nexus-snapshots</id>
		<name>Sonatype Nexus Snapshots</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
	</repository>
</repositories>
```
but didn't work for me.

**Comment by DirkMahler** [comment]
For the Maven plugin you'll need a pluginRepositories section like the following one:

```
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>
```
