### ISSUE TITLE
Constraint InjectablesMustNotBeInstantiated is too strict

### ISSUE THREAD

**Issue by hwellmann** [buschmais/jqa-spring-plugin#25]
In my projects, I'm getting InjectablesMustNotBeInstantiated violations for a pattern we use frequently:

````java
@Configuration
public class JacksonConfig {

    @Bean
    public ObjectMapper objectMapper() {
        return ObjectMapperFactory.createObjectMapper();
    }
}

public class ObjectMapperFactory {

    public static ObjectMapper createObjectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModules(new JavaTimeModule());
        return objectMapper;
    }
}
````
The static method allows us to use the same `ObjectMapper` definition both in Spring and non-Spring contexts (where non-Spring is not just test code - it is not unusual to have some other frameworks or libs within a Spring application which do not work with Spring beans).

Moving the constructor call to the producer method and then calling the producer method from `createObjectMapper()` would avoid the violation, but not really improve the code by introducing a dependency of the `ObjectMapperFactory` on Spring.

So my proposal is to rewrite the violation condition along the lines of "If the constructor of an Injectable is called *from another Injectable*, then the caller must be a BeanProducer".

````
MATCH
    (injectable:Injectable:Type)-[:DECLARES]->(constructor:Constructor),
    (type:Injectable:Type)-[:DECLARES]->(method:Method)-[newInstance:INVOKES*1..]->(constructor)
WHERE NOT (method:Spring:BeanProducer)
````

**Comment by DirkMahler** [comment]
Implemented the proposed approach, thanks for the suggestion!
