### ISSUE TITLE
spring-boot:Default causes false positives with dependency:PackageCycles

### ISSUE THREAD

**Issue by hwellmann** [buschmais/jqa-spring-plugin#26]
## Scenario

In my project, I'm using `spring-boot:Default` in combination with `dependency:PackageCycles`.

The analyzer reports a package cycle between two packages `service`  and `config`  that actually do not have a cycle.

## Analysis

Package `service` does depend on package `config`. A class in package `config` autowires `List<FooService>` where all beans implementing `FooService` are located in Package `service`. These beans are treated as a virtual dependency which results in the inverse relation

    config->[d:DEPENDS_ON]->service with d.virtual = true

Since the `PackageCycles` rule is not aware of the `virtual` flag, it will report a cycle between `service` and `config`.

## Proposal

Express virtual dependencies by a separate relation.

**Comment by DirkMahler** [comment]
Thanks for pointing to this, proposing to rename the relation to `VIRTUAL_DEPENDS_ON`.

**Comment by DirkMahler** [comment]
Done.
