### ISSUE TITLE
Controller annotated with @RestController is not view as Spring controller

### ISSUE THREAD

**Issue by murdos** [buschmais/jqa-spring-plugin#28]
`org.springframework.web.bind.annotation.RestController` annotation is itself annotated with `@Controller`

**Comment by DirkMahler** [comment]
For several reasons jQA does only scan the classes of a project but not the declared dependencies, e.g. Spring framework. Therefore the `@Controller` annotation therefore cannot be seen.

To solve this the next jQA release will come with concept that labels `@RestController` annotated classes with `Controller` and `RestController`.

**Comment by murdos** [comment]
Thanks for your answer, without it I was not sure how to fix this issue.
May I try to fix it by adding a new concept to https://github.com/jQAssistant/jqa-spring-plugin/blob/master/src/main/resources/META-INF/jqassistant-rules/spring-component.xml and open a PR?

**Comment by DirkMahler** [comment]
Thanks for offering, but I've already implemented it. Currently on testing it and some minor related improvements...
