### ISSUE TITLE
Rule for "A Spring service can only have dependencies to other Spring components that are services or repositories" is too strict

### ISSUE THREAD

**Issue by TheSasch** [buschmais/jqa-spring-plugin#40]
### Bug Description
When you have a Service which uses a MapStruct Mapper where one enitity will be mapped to a new format you got this message, becauce MapStruct generated `@Component` 

### Expected Behaviour
Don't show this Error on Components

### How can we reproduce the bug?
Create a Service which uses MapStruct to Map from one format to the other and scan this Service. Or just checkout

https://github.com/TheSasch/jqa_spring_example 

to see a demo application which shows the problem within the analysis. Use

`mvnw clean verify -P jqassistant `

to see the problem.

### Definition of Done for the Implementers
- [x] Integration tests have been written (_if applicable_)
- [x] Test coverage is the same or even better then before (_if applicable_)
- [x] Documentation has been written (_if applicable_)
- [x] Added a note on the new feature to the release notes (_if applicable_)

**Comment by DirkMahler** [comment]
The described behavior is by intention: a developer shall be forced to decide between Controller, Service or Repository - Component does not provide any information about the technical layer it belongs to (ok - this might be subject to discussion). Sadly in your situation the code is generated by MapStruct and you cannot influence it. But there's a way to suppress the generated constraint violation, I created a PR to your example project (thanks for providing this!) to illustrate that.

Nevertheless it seems that the Spring constraints should not apply to generated code, maybe can come up with a solution to this.

**Comment by DirkMahler** [comment]
@TheSasch Did the provided solution solve your issue?

**Comment by TheSasch** [comment]
Hello @DirkMahler,

i chatted about that topic in #jvm-german slack also with Oliver Drohtbohm and some other people the result was not as i throught at first. i thought about to generate a MapStruct Object which is also a `@Service`, because it's behavior in my software is something like business code. It maps an external interface which is provided by a REST service to an internal Entity. In my eyes the Mapper is also type of my business system and could be a stereotype `@Service` but there where no conclusion if a generated mapper is more a `@Component` instead, because this is a generic type. 

So Oli told me it would be great to setup this topic here. And now here it is. So i can understand everyone which says a mapper is more a Component and everyone who says a mapper is also part of the business code and when you read the stereotype description of Service than not only a REST-Service should be a service instead the whole business layer of the software could be stereotyped like this if it's not a entity, value object, repository or any of the other ddd stereotypes.

So the solution i think works for me here and now but the general problem if a abstract stereotype like component should not be linked within a service is still open in my eyes and Oli or other guys from SpringFramework should say something about that.

How about to put the pr you put on my repo as part of this ruleset? If you want, i know that you're also part of the slack take a look at the discussion.

BR
Sascha

**Comment by DirkMahler** [comment]
Just as an informration: as the issue was caused by generated code we new implemented another solution which allows labeling such classes as `Generated`, those would be excluded now from the Spring constraints. See https://github.com/jQAssistant/jqa-core-framework/issues/59.
