### ISSUE TITLE
Constraint: spring-injection:InjectablesMustOnlyBeHeldInInjectables - false positives?

### ISSUE THREAD

**Issue by mischa-n** [buschmais/jqa-spring-plugin#41]
First: Thanks a lot for providing jQAssistant. 

### Bug Description
The constraint spring-injection:InjectablesMustOnlyBeHeldInInjectables detects non-static inner classes of injectables, such inner classes always hold a reference to its owning class. 

### Expected Behaviour
Please modify this constraint.

### How can we reproduce the bug?
Example 1:
```
@Configuration
class ConfigurationWithInnerClass {

	@Bean
	HttpComponentsClientHttpRequestFactory httpRequestFactoryUsingInnerClass() {
		try {
			return new HttpComponentsClientHttpRequestFactory(HttpClientBuilder.create().useSystemProperties()
					.setSSLContext(new SSLContextBuilder().loadTrustMaterial(new TrustStrategy() {

						@Override
						public boolean isTrusted(X509Certificate[] chain, String authType) throws CertificateException {
							return true;
						}
					}).build()).build());
		} catch (KeyManagementException | NoSuchAlgorithmException | KeyStoreException e) {
			throw new RuntimeException(e);
		}
	}
}
```
results in NonInjectableHavingInjectablesAsField=ConfigurationWithInnerClass$1, Fields=ConfigurationWithInnerClass

Example 2:
```
@Component
public class ComponentWithInnerClass {

	private class InnerClassUsingSomeMethodFromOuterClass {

	}

}
```
results in NonInjectableHavingInjectablesAsField=ComponentWithInnerClass$InnerClassUsingSomeMethodFromOuterClass, Fields=ComponentWithInnerClass

**Comment by DirkMahler** [comment]
Issue could be reproduced, will be fixed in next release

**Comment by DirkMahler** [comment]
Anonymous inner classes (Non-Injectable) reference their outer class (Injectable) via a synthetic field - causing that false-positive.
