### ISSUE TITLE
Custom annotations with @RestController or @Component are getting wrong labels.

### ISSUE THREAD

**Issue by syabru** [buschmais/jqa-spring-plugin#44]
I have a custom annotation annotated with `@RestController`

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@RestController
public @interface MyCustomAnnotation {
}
```

which gets labelled with `Spring`, `RestController`, `Controller`, `Component`, `Injectable` by the `spring-mvc:RestController` concept. This leads to false positives with the `spring-component:ControllerMustOnlyDependOnServicesRepositories` constraint as annotation class is recognised as a controller, but actually is not.

`spring-mvc:RestController` concept should exclude annotations from being labelled. The same applies for the following concepts: `spring-component:Controller`, `spring-component:Service`, `spring-component:Component`, `spring-component:Configuration`, `spring-data:AnnotatedRepository`.

Current workaround is the following concept:

```
  <concept id="project:spring:AnnotationAnnotatedWithRestController">
    <providesConcept refId="spring-component:Component"/>
    <providesConcept refId="spring-component:Controller"/>
    <providesConcept refId="spring-injection:Injectable"/>
    <requiresConcept refId="spring-mvc:RestController"/>
    <description>
      Removes all Spring labels from annotations annotated with @RestController.
    </description>
    <cypher><![CDATA[
      MATCH (annotation:Annotation)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(annotationType:Type)
      WHERE annotationType.fqn = "org.springframework.web.bind.annotation.RestController"
     REMOVE annotation:Spring:RestController:Controller:Component:Injectable
     RETURN annotation as Annotation
    ]]></cypher>
  </concept>
```

**Comment by StephanPirnbaum** [comment]
We're moving closer to jQA 2.0.0. So closing this PR now. Please check the PR remarks in case you want to reopen it in the new repository.
