### ISSUE TITLE
[spring-injection:InjectablesMustNotBeInstantiated] Avoid Cartesian product. Ignore Generated types in call chain.

### ISSUE THREAD

**Issue by syabru** [buschmais/jqa-spring-plugin#45]
### Bug Description

Constraint `spring-injection:InjectablesMustNotBeInstantiated` builds Cartesian product when evaluating.

Constraint is violated if constructor of `Injectable` is called in call chain. If a `Generated` type is involved in the call chain, rule should not trigger.

**Comment by StephanPirnbaum** [comment]
We're moving closer to jQA 2.0.0. So closing this PR now. Please check the PR remarks in case you want to reopen it in the new repository.
